name: Build and release app

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    name: Build, sign and release app
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Build APK
        run: ./gradlew assembleRelease --no-daemon

      - name: Sign APK
        uses: ilharp/sign-android-release@v2
        id: sign
        with:
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      # Create a summary based on the latest fastlane metadata changelog
      - name: Create changelog summary
        id: changelog-summary
        run: |
            {
              summary_file=$(find fastlane/metadata/android/en-US/changelogs/ | sort -t '/' -k 6n | tail -n 1) # get name of latest changelog file
              summary_quoted=$(cat "$summary_file" | xargs -d '\n' -I {} echo "> {}") # prefix each line with "> "
              summary=$(echo -e "> [!NOTE]\n$summary_quoted") # format as GitHub markdown admonitions
              echo "summary<<EOF"$'\n'"$summary"$'\n'EOF >> $GITHUB_OUTPUT # make available as actions output
            }

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body:
            ${{ steps.changelog-summary.outputs.summary }}

            ${{ steps.changelog.outputs.changes }}
          files: ${{ steps.sign.outputs.signedFile }}
          fail_on_unmatched_files: true
          make_latest: true
