name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"
  push:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"

jobs:
  debug-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Check for Execution Orders
        run: |
          cd .github
          curl https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} > commit.json
          cd ..

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: Git Configuraion
        run: |
          git config --global user.name "Bnyro"
          git config --global user.email "bnyro@tutanota.com"
          git config --global credential.helper store
          echo "https://bnyro:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Compile
        run: |
          ./gradlew assembleDebug

      - name: Sign Apk
        continue-on-error: true
        id: sign_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/debug
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload to Archive
        continue-on-error: true
        run: |
          mv .github/uploader.py .
          echo "GH_REPO = '${{ github.repository }}'" > tgconfig.py
          git clone --filter=blob:none https://github.com/libre-tube/NightlyBuilds nightly
          rm -rf nightly/*.apk
          mv app/build/outputs/apk/debug/*.apk nightly/
          cd nightly
          python ../uploader.py
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: nightly/*.apk

